# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roasters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'
  pod 'FSCalendar'
  # Pods for Roasters

  target 'RoastersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoastersUITests' do
    # Pods for testing
  end

end
